<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_company</name>
   <tag></tag>
   <elementGuidId>211d77ae-2538-46dc-bacd-ad1eb78dafbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f17da92-cf22-403f-a2d8-ffcad84b2f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f1bbf3f-46ad-4318-afe1-f691b7c414eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>0daef703-701e-4ada-9fcc-da46cc502ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>ca0194b4-a701-4c3a-9687-effd6fb98f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>3dc7f586-ac3b-4889-92ba-55832a572b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>JC</value>
      <webElementGuid>195ec58b-13c0-4a99-9f69-ed4f8fc418a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>7f81c2f5-a9ad-4bc1-9077-53a3ab9b36fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_company&quot;)</value>
      <webElementGuid>c9c6d2ed-c37d-4170-9aae-1f5b35328bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_company']</value>
      <webElementGuid>d2d7971f-1e45-4036-bf0e-405dd3022465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_company_field']/span/input</value>
      <webElementGuid>5a15d361-6fa4-40cf-8989-5c9a4c7a38eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/input</value>
      <webElementGuid>8a25b4a3-66d9-45c0-a78a-8ceb70bd235a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_company' and @id = 'billing_company']</value>
      <webElementGuid>98096e85-2009-42ac-92c8-ed11a0919031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
